// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBufWxE2FWDr3vuiayriZueZzdHKQnGiSo',
    appId: '1:158153819260:web:49cd6bace9212962d5f5f9',
    messagingSenderId: '158153819260',
    projectId: 'fruit-market-5bc73',
    authDomain: 'fruit-market-5bc73.firebaseapp.com',
    storageBucket: 'fruit-market-5bc73.appspot.com',
    measurementId: 'G-4N3BSL3Q7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0GcQFxeudlyk1ydtGSweDuvKWRUo0I4',
    appId: '1:158153819260:android:c76bbb766f1bad21d5f5f9',
    messagingSenderId: '158153819260',
    projectId: 'fruit-market-5bc73',
    storageBucket: 'fruit-market-5bc73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-5AGxCVyrPsfhbmkBr2OL1Q7Ri0VXxI',
    appId: '1:158153819260:ios:672a5bbfb18e2669d5f5f9',
    messagingSenderId: '158153819260',
    projectId: 'fruit-market-5bc73',
    storageBucket: 'fruit-market-5bc73.appspot.com',
    iosBundleId: 'com.example.fruitMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-5AGxCVyrPsfhbmkBr2OL1Q7Ri0VXxI',
    appId: '1:158153819260:ios:672a5bbfb18e2669d5f5f9',
    messagingSenderId: '158153819260',
    projectId: 'fruit-market-5bc73',
    storageBucket: 'fruit-market-5bc73.appspot.com',
    iosBundleId: 'com.example.fruitMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBufWxE2FWDr3vuiayriZueZzdHKQnGiSo',
    appId: '1:158153819260:web:6dfbb91668b01700d5f5f9',
    messagingSenderId: '158153819260',
    projectId: 'fruit-market-5bc73',
    authDomain: 'fruit-market-5bc73.firebaseapp.com',
    storageBucket: 'fruit-market-5bc73.appspot.com',
    measurementId: 'G-SDD6DHCMSL',
  );
}
